### ISSUE TITLE
Parameter extra_samples is not optional

### ISSUE THREAD

**Issue by JWahle** [scripple/alsa_cdsp#1]
Hi,
thanks for this plugin - works great.

I just got confused a little by the documentation saying that the parameter `extra_samples` is optional in the alsa config.
Leaving it out results in the following error message:
`error: Invalid value for '--extra_samples <extra_samples>': Must be an integer > 0`

It seems that the plugin sets it to `0` instead of leaving out the parameter.
Another option might be, to set it to `1` - AFAIK this should not result in a noticeable difference.
For `config_cdsp 1` not passing the parameter to CamillaDSP would be the best option, since it can then be set inside the config - without reloading ALSA.

**Comment by scripple** [comment]
Are you using config_cdsp mode?

**Comment by JWahle** [comment]
Yes, I use `config_cdsp 1`.
In that case I would expect to have no `-e ...` parameter passed to CamillaDSP.

I also tried `config_out` - which results in the same error message.

**Comment by scripple** [comment]
config_out is always required.  

At the time config_cdsp mode was written CamillaDSP didn't actually accept command line parameters so it couldn't be tested.  I'll fix it to not emit the option when it is zero.

**Comment by scripple** [comment]
Please try the just pushed commit.  It should work without config_cdsp = 1 and extrasamples 0 or undefined.

**Comment by HEnquist** [comment]
Setting extra_samples to 0 is valid and CamillaDSP should accept that. But there is a typo, the check is > 0 instead of >= 0. I'll fix that!

**Comment by scripple** [comment]
I'll leave the code to omit the -e when extrasamples is 0 as it's done.  Seems this is likely fixed from both sides now.  Closing.

**Comment by JWahle** [comment]
Sounds perfect to me - thanks :+1:

**Comment by scripple** [comment]
> Setting extra_samples to 0 is valid and CamillaDSP should accept that. But there is a typo, the check is > 0 instead of >= 0. I'll fix that!

Actually I wonder if I should let -e 0 pass.  I suppose it's possible someone might be overriding a config with a default not zero.

**Comment by JWahle** [comment]
So you are saying that it should work as follows:
- extra_samples not set in ALSA plugin config => CamillaDSP will be called without -e argument
- extra_samples set to 0 => CamillaDSP will be called with -e 0 argument
Correct?

In that case, I would agree.

**Comment by scripple** [comment]
Done including updates to readme/asound.conf
