### ISSUE TITLE
Option to specify log file

### ISSUE THREAD

**Issue by JWahle** [scripple/alsa_cdsp#2]
I would like to have the option to specify a log file for CamillaDSP output.
Currently, logs are written by the calling application, which I don't maintain.
So I have no control over where the log output goes.
Changing the log level might also be useful to some, though I personally don't need it.

**Comment by scripple** [comment]
That request should be made of the CamillaDSP project.  Any command line arguments for it can be passed through this plugin with the cargs config.  You can already set the CamillaDSP log level via the same method.

**Comment by JWahle** [comment]
You're right, the log level can already be set through your plugin.
However, under Linux you can run `camilladsp config.yaml > log.txt` and you redirect the output to log.txt.
When I run CamillaDSP myself, this is possible.
I could not find a way to do this through your plugin.

**Comment by scripple** [comment]
Correct you can't do that, but others have asked Henrik to add a log file option to CamillaDSP and I think that's where it should be handled.  Ideally this plugin would have no output of its own, but has a little still on for major failures as it's new.
